language: node_js
node_js:
  - 8
cache:
  directories:
    - $HOME/.npm

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

before_script:
  - npm prune
after_success:
  - npm run semantic-release
script: npm run $COMMAND
env:
  matrix:
    - COMMAND=pretest # linting
    - COMMAND=record
    - COMMAND=test:unit
    - COMMAND=test:integration
    - COMMAND=test:scenarios
    - COMMAND=test:e2e:server
    - COMMAND=test:e2e:external-fixtures

matrix:
  fast_finish: true
  include:
    - node_js: "4"
      env: COMMAND=test:node4
  allow_failures:
    - node_js: "8"
      env: COMMAND=coverage:upload

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run semantic-release
