language: node_js
node_js:
  - 8
cache:
  directories:
    - $HOME/.npm

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

script: npm run $COMMAND

jobs:
  include:
    - stage: lint
      env: COMMAND=pretest
    - stage: test
      env: COMMAND=record
    - env: COMMAND=test:unit
    - env: COMMAND=test:integration
    - env: COMMAND=test:scenarios
    - node_js: 4
      env: COMMAND=test:node4
    - stage: release
      node_js: lts/*
      env: COMMAND=semantic-release
  allow_failures:
    - node_js: "8"
      env: COMMAND=coverage:upload

stages:
  - lint
  - test
  - name: release
    if: branch = master AND type IN (push)
