language: node_js
cache:
  directories:
    - $HOME/.npm
node_js:
  - 8
before_script:
  - npm prune
after_success:
  - npm run semantic-release
script: npm run $COMMAND
env:
  matrix:
    - COMMAND=pretest # linting
    - COMMAND=record
    - COMMAND=test:unit
    - COMMAND=test:integration
    - COMMAND=test:e2e
    - COMMAND=coverage:upload

matrix:
  fast_finish: true
  include:
    - node_js: "4"
      env: COMMAND=test:node4
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
